spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: pricer
    producer:
      retries: 0
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
auto:
  create:
    topics:
      enable: true

management:
  endpoint:
    info:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true

kafka:
  listener:
    order:
      autoStart: false
    price:
      autoStart: false

togglz:
  console:
    path: /togglz-console
    enabled: true
  enabled: true