spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: pricer
    producer:
      retries: 0
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer